name: finger_like
description: "一个简单的鼠标连点器。"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  async: ^2.11.0  # 新增异步处理依赖
  provider: ^6.1.1  # 新增状态管理

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
