name: finger_like
description: "一个简单的鼠标连点器。"
publish_to: 'none'

version: 0.0.1+1
organization: "shichen437"

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  window_manager: ^0.3.1
  hotkey_manager: ^0.2.0
  cupertino_icons: ^1.0.8
  async: ^2.11.0
  provider: ^6.1.1
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.12
  win32: ^5.12.0
  ffi: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/trans/
